site_name: Actividades de FÃ­sica
theme:
  name: material

nav:
  - ğŸ  IntroducciÃ³n: index.md
  - ğŸ›¡ï¸ Normas de Seguridad: Safety.md
  - ğŸ“š ProgramaciÃ³n y Actividades:
      - ğŸ“˜ FIME:
          - ğŸ—‚ï¸ ProgramaciÃ³n: FIME/index.md
          - TeorÃ­a de errores: FIME/actividad-1.md
          - Slinky: FIME/actividad-2.md
          - MediciÃ³n de g: FIME/actividad-3.md
          - CinemÃ¡tica en el plano inclinado: FIME/actividad-4.md
          - Fuerza de fricciÃ³n: FIME/actividad-5.md
          - ConservaciÃ³n de la energÃ­a: FIME/actividad-6.md
          - DinÃ¡mica rotacional: FIME/actividad-7.md
          - Principio de ArquÃ­medes: FIME/actividad-8.md

      - ğŸ“— FIS1:
          - ğŸ—‚ï¸ ProgramaciÃ³n: FIS1/index.md
          - TeorÃ­a de errores: FIS1/actividad-1.md
          - Slinky: FIS1/actividad-2.md
          - MediciÃ³n de g: FIS1/actividad-3.md
          - CinemÃ¡tica en el plano inclinado: FIS1/actividad-4.md
          - Movimiento armÃ³nico simple: FIS1/actividad-5.md
          - Fuerza de fricciÃ³n: FIS1/actividad-6.md
          - ConservaciÃ³n de la energÃ­a: FIS1/actividad-7.md
          - Ondas en una cuerda: FIS1/actividad-8.md

      - âš¡ FIEM:
          - ğŸ—‚ï¸ ProgramaciÃ³n: FIEM/index.md
          - Instrumentos de mediciÃ³n: FIEM/actividad-1.md
          - FenÃ³menos ElectroestÃ¡ticos: FIEM/actividad-2.md
          - Ley de Coulomb: FIEM/actividad-3.md
          - Generador de Van de Graaff: FIEM/actividad-4.md
          - Carga y Descarga de un Condensador: FIEM/actividad-5.md
          - Coeficiente T de la resistencia (Cu): FIEM/actividad-6.md
          - Ley de Ohm y Kirchhoff: FIEM/actividad-7.md
          - Campo magnÃ©tico terrestre: FIEM/actividad-8.md
          - Permeabilidad magnÃ©tica del aire: FIEM/actividad-9.md

      - ğŸ§² FIS2:
          - ğŸ—‚ï¸ ProgramaciÃ³n: FIS2/index.md
          - Instrumentos de mediciÃ³n: FIS2/actividad-1.md
          - FenÃ³menos ElectroestÃ¡ticos: FIS2/actividad-2.md
          - Ley de Coulomb: FIS2/actividad-3.md
          - Generador de Van de Graaff: FIS2/actividad-4.md
          - Carga y Descarga de un Condensador: FIS2/actividad-5.md
          - Ley de Ohm y Kirchhoff: FIS2/actividad-6.md
          - Campo magnÃ©tico terrestre: FIS2/actividad-7.md
          - Ley de Lenz: FIS2/actividad-8.md
          - Ondas estacionarias: FIS2/actividad-9.md
          - Dimensiones microscÃ³picas con lÃ¡ser: FIS2/actividad-10.md

      - ğŸ§ª FCOP:
          - ğŸ—‚ï¸ ProgramaciÃ³n: FCOP/index.md
          - PÃ©ndulo simple y masaâ€“resorte: FCOP/actividad-1.md
          - PÃ©ndulo compuesto: FCOP/actividad-2.md
          - Oscilaciones forzadas: FCOP/actividad-3.md
          - Ondas estacionarias: FCOP/actividad-4.md
          - Concentraciones de azÃºcar: FCOP/actividad-5.md
          - Interferencia y difracciÃ³n: FCOP/actividad-6.md
          - Dimensiones microscÃ³picas con lÃ¡ser: FCOP/actividad-7.md

  - ğŸï¸ Animaciones:
      - Oscilaciones: Animaciones/anim-1.md
